### ISSUE TITLE
Remove governance constants

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1113]
As of #1109 we export an object of `committeeIds` which is intended to hold constant ID values for the various committees on a per-chain basis. These should be added as soon as the relevant chains have been deployed. Same applies to `guaranteeFundEscrowIds` and `rewardFundAddresses`.

**Comment by webmaster128** [comment]
Is this in scope of IOV-Core? I think this should remain configurable, such that the wallet can use different values for the development/staging/production networks using different config files.

**Comment by webmaster128** [comment]
It turns out that those values can very well be managed in the network-dependent configuration files of the governance app. New id to address helpers have managing the addresses sufficiently convenient. For this reason we should instead remove the entire `./committees` module as well as the reference in `const { /* committeeIds, guaranteeFundEscrowIds, */ Governor, ProposalType } = require("@iov/bns-governance");`
