### ISSUE TITLE
Implement retries into WS and HTTP RPC

### ISSUE THREAD

**Issue by Isabello** [iov-one/iov-core#229]
Right now, when we connect to WS(s) or HTTP(s) RPC, it only tries once. We should allow for retries before throwing completely.

Additionally, being able to retry the connection if we lose it would be helpful as well.

- [x] Implement a queueing wrapper around `StreamingSocket` with a non-blocking send function
- [x] Implement reconnects that send messages from the queue via the new connection as soon as established
- [x] Expose connected state (connecting, connected, disconnected) as a `ValueAndUpdates` field (Because we can. It is a fair API, but not strictly required for the product)
- [x] Make it possible for higher level applications to react to reconnects via a simple `reconnected` callback
- [x] Automatically reconnect on error/completion
- [x] Automatically re-subscribe in tendermint-rpc
- [x] Automatically re-subscribe in ethereum

**Comment by ethanfrey** [comment]
This happens in the web-wallet when there is connectivity break and afaik, it cannot recover without reloading the app. This "reload" will be a bit harder with an extension.

Reconnecting on network failure is important, so the next call may succeed.

However, we must also consider subscriptions and how to handle that when it break?
Do we re-subscribe? What about items lost in the meantime? There needs to be some higher-level logic at work.

eg. I use `liveTx` to search and subscribe for all tx that match my account. I lose connectivity and reconnect 2 minutes later, missing a tx event. If I auto-resubscribe I will never get that one (but will get future ones). To handle it properly, we must notifiy so the higher level code (eg liveTx can do a search since last receive and then subscribe again).

Properly handling subscriptions can be done later. This should allow:
* minimally a reconnect, so a query will work later
* optionally reconnect the subscriptions as well (even if there is a gap they will miss)

**Comment by willclarktech** [comment]
@webmaster128 What's the scope of this issue? `tendermint-rpc` only or others as well?

**Comment by webmaster128** [comment]
> What's the scope of this issue?

Preferribly lower level to cover `tendermint-rpc` as well as `ethereum`. I guess an auto-queueing and auto-reconnecting socket wrapper in @iov/sockets makes sense.

**Comment by ethanfrey** [comment]
Yes, it would be good to auto-reconnect for long-term stability.

The one issue is that this information of a reconnect must be passed to the higher-level handler.
If a tendermint connection opens a number of subscriptions for account updates, then the lower-level websocket reconnects, we will also want to re-create those subscriptions.

This part cannot be done in `@iov/sockets`, but if it had a callback after connection break and successful re-establishment, that part could be done in a higher level. I think we would need similar app-specific logic in iov-bns as well as iov-ethereum

**Comment by webmaster128** [comment]
Good point @ethanfrey

To break this down into smaller steps, I suggest

1. Implement a queueing wrapper around `StreamingSocket` with a non-blocking send function
2. Implement reconnects that send messages from the queue via the new connection as soon as established
3. Expose connected state (connecting, connected, disconnected) as a `ValueAndUpdates` field (Because we can. It is a fair API, but not strictly required for the product)
4. Make it possible for higher level applications to react to reconnects via a simple `reconnected` callback
5. Automatically re-subscribe in tendermint-rpc
6. Automatically re-subscribe in ethereum

**Comment by willclarktech** [comment]
^ Added this as a checklist to the issue description.

**Comment by ethanfrey** [comment]
I agree with the above list. I think it still has some utility even in smaller chunks, maybe a series of PRs.
