### ISSUE TITLE
Improve separation of concerns, public APIs

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#301]
This is a mega-issue to work on redesigning how to expose the query/signing functionality in a safe, flexible, extensible way. We have a working architecture, and it is not used in a UI, but currently all code is in the same process. This can work for eg. an electron app, but if we wish to work in a browser, we need to the key management into an extension or native app.

A number of related issues have arisen, notably #222 and #223 which were a first attempt to define separation, and #291. Ledger support in #256 also seems to require placing the key management out of process from any chrome extension.

This issue attempts to close many of the referenced issues above with a clean and extensible architecture. The design work will be done in a PR for comments and collaboration. The main thought is to separate into three components (which can be in the same process or different ones).

* **Untrusted UI / App** - this can be a webapp, etc. where we would like to be correct, but cannot forge transactions if compromised. This part can then iterate quickly, import plugins, etc. This allows a very flexible "reader" API for use here.
* **Trusted UI / Signer** - this is a signed, downloaded executable that talks to the *Untrusted UI* and provides information for the user to approve transactions before signing them. It also provides an interface to create new accounts and expose identities to the *Untrusted API*. This part must be able to communicate with the blockchain to query nonces, submit transactions, check codecs, etc...
* **Keyring** - the keyring provides an interface to signing with key material. It trusts the app that connects to it (*Trusted UI*), meaning it will sign whatever it is requested to sign, but it will never leak private key material across this boundary. This should usually be on the same machine as the *Trusted UI* and may run as a background daemon.

We also assume that there may be a 1:N / N:N relationship at any of these stages (to be implemented in the future, but at least included in the design).  That is, an app may call (one of) multiple signers, something like https://walletconnect.org/. Also, a Signer may need multiple key stores to back it, such as a chrome extension that stores software keys internally, but calls out to a local node app to talk to the ledger, as extensions cannot talk to a ledger.... 

- [x] Accepted PR for new architecture design (markdown)
- [x] Accepted PR implementing new architecture
- [ ] Implement some examples for out-of-process use case.

**Comment by ethanfrey** [comment]
Hi @lazaridiscom thanks for the comments.

Yeah, we wanted a library for our blockchain providing metamask-like functionality, as it is the most developer-friendly tooling I have seen. I read through metamask code first to see if we could fork it easily. Turns out it is quite tied to web3 all the way down to the signing layer, so we built this from the ground up. But I did grab some terms like Keyring from the metamask project.

If you are abandoning those terms, we should definitely take note.
@Isabello please take a look at https://github.com/lazaridiscom/mm-vault/blob/master/dev/terminology.md#draft especially Account, Address, Wallet, Vault. This may clean up some of the name confusion we have been fighting with as well.

**Comment by lazaridiscom** [comment]
> If you are abandoning those terms, we should definitely take note.

Note that I'm not anymore active within the MetaMask project (I had asked for limited 3 months contract). Although I still keep an eye on it.

Work within https://github.com/lazaridiscom/mm-vault/ is essentially a started redesign of the KeyringController (1st redesign step was the renaming to "mm-vault")

Besides the "keyring" term, another major source of confusion was a miss-naming within an `ethereumjs-wallet` library ("wallet" instead of "account"). Se the code-level changes to understand the terrible effect of just **one** false term:

https://github.com/lazaridiscom/mm-vault/commit/88bc08601f556a0e87b1827e785dc031418a09bb

after renaming ethereumjs-wallet's "wallet" to "address" and MetaMask's "keyring" to "wallet", everything became crystal-clear, especially after reviewing the Trezor Diagram:

https://blog.trezor.io/wallet-accounts-and-addresses-bdfa6b66b037

Those renaming/redesign enabled my (previously near totally blocked) architectural thinking again. I saw the need for a meta-data-driven UI, to enable multiple wallet-providers - or "keyrings", in the old terminology.

MetaMask implemented several of my suggested changes, but not all. It kept the original naming and (non meta-data-driven, non generic) architecture.

Essence: The term "keyring" will most possibly survive there at MetaMask.

Now, the terminology-document is essentially an evolving document. I understand e.g. that you are implementing something like a "SuperVault" or "MegaWallet" or "UniWallet" - possibly even "THE (Bockchain) Vault". One could extent the document for higher-graded constructs, and at the same time revise/refine the existent terminology.

Enough!

Me dizzy now!

**Comment by ethanfrey** [comment]
Okay, I think it is important to take a pass through all the major types exposed through @iov/core to make sure we are pretty happy with them, so we can get some stability for the wallet before they tag a release (rather than immediately breaking)

**Comment by ethanfrey** [comment]
Mostly done, and closing last point in favor of issue #575
