### ISSUE TITLE
@iov/ledger-bns should get id from first connection with app

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#334]
#332 added `id` to all keyring entries, which is tied to the cryptographic secret stored inside. (no private info is revealed, but we can do an equality check as to whether they have the same secret information inside).

With the ledger, we should grab for example, a hash for the publickey at index 0. Unfortunately we can only do this asynchrnously once it is connected with the app open.

We should check every time we connect to the app. If the id was unset before, set to the id derived from the current ledger. If we connect to a ledger and it has a different derived id that what is stored in our currenly open keyring, maybe throw an error?We need a separatekeyring, as the locally stored public keys don't reflect the ledger device.

**Comment by webmaster128** [comment]
I don't think binding the device to the wallet id is the best solution (partly due to the problems described above). I'd prefer to use auto-generated IDs for the wallets like we have with the other wallets as well. As a second step, a wallet can then be bound to a device and refuse to work when the wrong device is connected: https://github.com/iov-one/iov-core/issues/490
