### ISSUE TITLE
Tendermint start script breaks with default OSX settings

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#775]
By default the OSX `TMPDIR` is set to a directory which is not included in Docker for Mac's default list of File Sharing directories. So running `./scripts/tendermint/start.sh` fails with a slightly offputting message:

> The path [...] is not shared from OS X and is not known to Docker.

It would be good to cover this case in the README, either by telling users that if it happens they should adjust their File Sharing preferences in Docker or (probably better) just overriding the `TMPDIR` value:

```
TMPDIR="" ./scripts/tendermint/start.sh
```

**Comment by webmaster128** [comment]
> either by telling users that if it happens they should adjust their File Sharing preferences in Docker or (probably better) just overriding the `TMPDIR` value

I prefer telling the user to whitelist the $TMPDIR. Fortunatly that randomly generated path never changes over the lifetime of a macOS system user, so you only have to add the directory once. Setting `TMPDIR=""` probably leads to using /tmp which does not seem to be the preferred place on macOS.

Since this issue is the same for all our start scritps, we should have it somewhere in the root README.
